OUTEXT=
OBJ=o

COMMON_FLAGS=-DUNIX=1 -Werror -Wextra -Wall -Wconversion
#SANITIZERS=-fsanitize=address -fsanitize=undefined
DEBUG_FLAGS=-g -O0 $(COMMON_FLAGS) $(SANITIZERS)
RELEASE_FLAGS=-Os $(COMMON_FLAGS)

BUILD=$(RELEASE_FLAGS)

CXXFLAGS=$(BUILD) -std=c++17
CFLAGS=$(BUILD) -std=c17 -Ibase

LDFLAGS=$(SANITIZERS)
LDLIBS=
RM=rm -f
