name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: init-submodules
      run: git submodule update --init --recursive
    - name: config
      run: ln -s unix.mk config.mk
    - name: make
      run: make
